### ISSUE TITLE
Data split error

### ISSUE THREAD

**Issue by taokz** [illidanlab/SplitMix#1]
Hi

Firstly, thank you for your good work. 

I've encountered a data split error when I set number of clients as 100 (partition rate = 0.1, 10 clients per round), ```pu_class = 5``` and run ```fedavg.py```:
```console
ValueError: Not enough samples. Require 64 samples per share at least for 50 shares. But only 1000 is available totally.
``` 
Could you give me some suggestions? Thanks!

**Comment by jyhong836** [comment]
Hi,

Thanks for being interested in our project.

Can you kindly provide more information on the issue?

1. I did not find `partition_ratio` in my codes. Is there any typo?
2. What data set do you use?
3. Can you check if this happens with the val or training data split?

**Comment by taokz** [comment]
Hi, thank you for your reply.

1. I set ```pr_nuser = 10, pd_nuser = 100```
2. Cifar10 dataset
3. The training and validation data split works well as shown in the following:

```console
 train size: [50000] 
 test  size: [10000] 
 trimmed train size: [50000] 
 class-6 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-9 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-4 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-1 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-2 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-7 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-8 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-3 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-5 => 50 shares 
  5000 smp => 50 shards by uni distr 
 class-0 => 50 shares 
  5000 smp => 50 shards by uni distr 
 0 | train split size: [500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500] 
    | train classes: ['[0, 2, 4, 6, 9]', '[1, 3, 5, 7, 8]', '[2, 3, 4, 5, 8]', '[0, 1, 6, 7, 9]', '[0, 1, 2, 5, 7]', '[3, 4, 6, 8, 9]', '[0, 1, 3, 5, 7]', '[2, 4, 6, 8, 9]', '[0, 3, 5, 6, 8]', '[1, 2, 4, 7, 9]', '[2, 5, 6, 8, 9]', '[0, 1, 3, 4, 7]', '[0, 1, 3, 5, 7]', '[2, 4, 6, 8, 9]', '[2, 3, 5, 6, 7]', '[0, 1, 4, 8, 9]', '[1, 2, 3, 5, 8]', '[0, 4, 6, 7, 9]', '[0, 3, 4, 6, 7]', '[1, 2, 5, 8, 9]', '[0, 1, 3, 6, 8]', '[2, 4, 5, 7, 9]', '[1, 2, 6, 8, 9]', '[0, 3, 4, 5, 7]', '[1, 3, 6, 7, 9]', '[0, 2, 4, 5, 8]', '[1, 2, 4, 5, 6]', '[0, 3, 7, 8, 9]', '[0, 2, 3, 5, 6]', '[1, 4, 7, 8, 9]', '[3, 4, 5, 7, 8]', '[0, 1, 2, 6, 9]', '[1, 2, 3, 8, 9]', '[0, 4, 5, 6, 7]', '[0, 3, 4, 5, 7]', '[1, 2, 6, 8, 9]', '[3, 4, 5, 6, 9]', '[0, 1, 2, 7, 8]', '[0, 2, 4, 7, 9]', '[1, 3, 5, 6, 8]', '[1, 2, 3, 4, 8]', '[0, 5, 6, 7, 9]', '[0, 2, 4, 7, 8]', '[1, 3, 5, 6, 9]', '[0, 1, 3, 5, 6]', '[2, 4, 7, 8, 9]', '[2, 4, 7, 8, 9]', '[0, 1, 3, 5, 6]', '[1, 5, 6, 8, 9]', '[0, 2, 3, 4, 7]', '[1, 2, 3, 7, 9]', '[0, 4, 5, 6, 8]', '[0, 1, 2, 3, 8]', '[4, 5, 6, 7, 9]', '[3, 4, 6, 7, 9]', '[0, 1, 2, 5, 8]', '[4, 6, 7, 8, 9]', '[0, 1, 2, 3, 5]', '[0, 1, 3, 6, 8]', '[2, 4, 5, 7, 9]', '[0, 4, 6, 7, 9]', '[1, 2, 3, 5, 8]', '[0, 2, 6, 8, 9]', '[1, 3, 4, 5, 7]', '[1, 4, 5, 8, 9]', '[0, 2, 3, 6, 7]', '[1, 4, 7, 8, 9]', '[0, 2, 3, 5, 6]', '[1, 4, 6, 7, 8]', '[0, 2, 3, 5, 9]', '[0, 1, 6, 7, 9]', '[2, 3, 4, 5, 8]', '[1, 2, 6, 7, 9]', '[0, 3, 4, 5, 8]', '[3, 4, 5, 6, 8]', '[0, 1, 2, 7, 9]', '[0, 1, 2, 4, 7]', '[3, 5, 6, 8, 9]', '[0, 3, 5, 6, 8]', '[1, 2, 4, 7, 9]', '[0, 1, 4, 5, 9]', '[2, 3, 6, 7, 8]', '[0, 1, 4, 5, 9]', '[2, 3, 6, 7, 8]', '[0, 2, 4, 6, 7]', '[1, 3, 5, 8, 9]', '[0, 1, 5, 6, 7]', '[2, 3, 4, 8, 9]', '[0, 4, 6, 8, 9]', '[1, 2, 3, 5, 7]', '[1, 2, 5, 7, 9]', '[0, 3, 4, 6, 8]', '[2, 3, 4, 6, 9]', '[0, 1, 5, 7, 8]', '[4, 5, 6, 7, 8]', '[0, 1, 2, 3, 9]', '[1, 2, 6, 8, 9]', '[0, 3, 4, 5, 7]', '[0, 1, 2, 3, 7]', '[4, 5, 6, 8, 9]'] 
 class-3 => 50 shares 
  1000 smp => 50 shards by uni distr 
Traceback (most recent call last): 
  File "fed_hfl.py", line 124, in <module> 
    fed = Federation(args.data, args) 
  File "/home/kaz/SplitMix/federated/core.py", line 154, in __init__ 
    super(HeteFederation, self).__init__(data, args) 
  File "/home/kaz/SplitMix/federated/core.py", line 89, in __init__ 
    consistent_test_class=args.con_test_cls, 
```

**Comment by jyhong836** [comment]
What is your `pu_nuser`? I would recommend `3` or a smaller value.

Please refer to [sweeps/fed_class_niid/cifar10.yaml](https://github.com/illidanlab/SplitMix/blob/master/sweeps/fed_class_niid/cifar10.yaml) for detailed configurations for the class non-iid setting.

**Comment by taokz** [comment]
I set ```pu_nuser=5```.

**Comment by taokz** [comment]
Do you mean ```pu_nclass```? I set it as 5.

**Comment by jyhong836** [comment]
Yes. `pu_nclass`. It may be too large for the test set.

**Comment by jyhong836** [comment]
Alternatively, you may change the minimal allowed samples in [here](https://github.com/illidanlab/SplitMix/blob/4297aa01a90101792bfb482fd96a61f51766d97a/utils/data_loader.py#L341)

**Comment by taokz** [comment]
ok, thanks!
